repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-merge-conflict
    exclude: ^vendor/
  - id: end-of-file-fixer
    exclude: ^vendor/
  - id: detect-private-key

- repo: https://github.com/ambv/black
  rev: 21.7b0
  hooks:
  - id: black
    exclude: ^vendor/
    language_version: python3.10

- repo: git://github.com/dnephin/pre-commit-golang
  rev: v0.4.0
  hooks:
    - id: go-fmt
      exclude: ^vendor/
    - id: go-lint
      exclude: ^vendor/
    - id: go-imports
      exclude: ^vendor/
    - id: golangci-lint
      args: [--verbose]
      exclude: ^vendor/

- repo: local
  hooks:
    - id: sbom
      name: syft
      entry: .git/hooks/sbom.sh
      language: system
